export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";


export const EDIT_PROFILE_LOADING = "RESET_PASSWORD_LOADING";
export const EDIT_PROFILE_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const EDIT_PROFILE_ERROR = "RESET_PASSWORD_ERROR";

export const CHANGE_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";


export const VERIFY_LOADING = "VERIFY_LOADING";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_ERROR = "VERIFY_ERROR";


export const DELETE_ACCOUNT_LOADING = "DELETE_ACCOUNT_LOADING";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";
